name: CD - Production Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: production-deploy
  cancel-in-progress: false

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production   # approval gate works here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =====================
      # AWS AUTH
      # =====================
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # =====================
      # GCP AUTH
      # =====================
      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # =====================
      # TERRAFORM
      # =====================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # =====================
      # DEPLOY AWS (ECS)
      # =====================
      - name: Deploy AWS Production
        working-directory: terraform/aws
        run: |
          export TF_INPUT=0
          terraform init -upgrade

          terraform apply -auto-approve \
            -var="backend_image=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-backend:${{ github.sha }}" \
            -var="frontend_image=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-frontend:${{ github.sha }}"

      # =====================
      # DEPLOY GCP (CLOUD RUN)
      # =====================
      - name: Deploy GCP Production
        working-directory: terraform/gcp
        run: |
          export TF_INPUT=0
          terraform init -upgrade

          terraform apply -auto-approve \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="backend_image=${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/devops/backend:${{ github.sha }}" \
            -var="frontend_image=${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/devops/frontend:${{ github.sha }}"
