name: CD - Deploy (AWS + GCP)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # AWS Auth
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # GCP Auth
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: hashicorp/setup-terraform@v3

      # ---------- AWS Deploy ----------
      - name: Terraform Apply (AWS)
        working-directory: terraform/aws
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="backend_image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-backend:${{ github.sha }}" \
            -var="frontend_image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-frontend:${{ github.sha }}"

      # ---------- GCP Deploy ----------
      - name: Terraform Apply (GCP)
        working-directory: terraform/gcp
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="project_id=$GCP_PROJECT_ID" \
            -var="region=$GCP_REGION" \
            -var="backend_image=$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/devops/backend:${{ github.sha }}" \
            -var="frontend_image=$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/devops/frontend:${{ github.sha }}"
