name: CD - Staging Deploy (AWS + GCP)

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- AWS AUTH ----------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------------- GCP AUTH ----------------
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ---------------- Terraform ----------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ---------------- AWS STAGING ----------------
      - name: Deploy AWS Staging
        working-directory: terraform/aws
        run: |
          terraform init -upgrade
          terraform apply -auto-approve \
            -var="backend_image=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-backend:${{ github.sha }}" \
            -var="frontend_image=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-frontend:${{ github.sha }}"

      # ---------------- GCP STAGING ----------------
      - name: Deploy GCP Staging
        working-directory: terraform/gcp
        run: |
          terraform init -upgrade
          terraform apply -auto-approve \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION }}" \
            -var="backend_image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/devops/backend:${{ github.sha }}" \
            -var="frontend_image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/devops/frontend:${{ github.sha }}"
