name: Terraform Destroy (GCP)

on:
  workflow_dispatch:   # manual trigger

env:
  PROJECT_ID: united-firefly-252203
  REGION: us-central1

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/gcp
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/gcp
        run: |
          terraform destroy -auto-approve -input=false \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="backend_image=dummy" \
            -var="frontend_image=dummy"
